default_stages: [pre-commit, pre-push, manual]
fail_fast: false

repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.9.13
    hooks:
      - id: uv-lock

  - repo: https://github.com/psf/black
    rev: 25.11.0
    hooks:
      - id: black

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.7
    hooks:
      - id: ruff-check

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.0
    hooks:
      - id: mypy
        additional_dependencies:
          - "aiosqlite>=0.21.0"
          - "fastapi>=0.119.1"
          - "pyjwt>=2.10.1"
          - "pydantic-settings>=2.12.0"
          - "pwdlib[argon2]>=0.3.0"
          - "python-magic-bin>=0.4.14 ; sys_platform == 'win32'"
          - "python-magic>=0.4.27 ; sys_platform != 'win32'"
          - "scalar_fastapi>=1.4.3"
          - "sqlalchemy>=2.0.44"
          - "types-aiofiles>=25.1.0.20251011"
          - "uvicorn>=0.38.0"
        args: ["--strict"]
